### PR TITLE
Clean up main.C and explicitly register dependent app

### PR DESCRIPTION
**Pull request by MengnanLi91**
Adapt to the new changes in MOOSE(https://github.com/idaholab/moose/pull/25994)

### CODE REVIEW

**Comment by MengnanLi91** [comment]
@mangerij Could you help me review this patch PR?

**Comment by MengnanLi91** [comment]
Hi @mangerij, could you let me know what the failure messages are for the tests? I don't have access to that information.

**Comment by MengnanLi91** [comment]
> I can see it - It's because the PR isn't based on devel.
> 
> Oops....I just changed this, and it seems to have mucked up your history a little bit. If you don't mind, I can fix this for you since it was my fault.

Oh oh I didn't realize it. Yeah, go ahead. Thanks a lot!

**Comment by mangerij** [comment]
@cticenhour Hi,
I'll give a look later today at the changes to name.C. (sorry for the delay, I don't have GH notifs sent to my work email -will change)
 
MSCA diffs are slightly alarming. Are you sure they are actually diffing? I checked a recent PR and Ferret seems to be building and passing tests no problem.

https://civet.inl.gov/job/2011110/

**Comment by cticenhour** [comment]
I am on an Apple Silicon Mac, so there is likely just a platform related diff here. I can double check on a Linux system later this morning when I get to the office.

**Pull request merged**
