### PR TITLE
Rename TM module 

### PR DESCRIPTION
**Pull request by GiudGiud**
refs https://github.com/idaholab/moose/issues/25584

~~not ready for merge~~

### CODE REVIEW

**Comment by GiudGiud** [comment]
Looks like we just pull master for Ferret testing. 
This should pass naturally in a couple of days @mangerij , just need to wait on the change in MOOSE to make it through

**Comment by mangerij** [comment]
@GiudGiud Thanks! let me know when I should merge...

**Comment by GiudGiud** [comment]
This is good to go now!

**Comment by GiudGiud** [comment]
@mangerij for your consideration

**Comment by mangerij** [comment]
@GiudGiud very sorry that I took 2 weeks to merge it... !!! I don't know why Github does not send emails notifications to my main email. I should fix that...

@heinono1 it is merged now, thanks for the email heads up :)

**Pull request merged**
